server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: gymjjak-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: "gymjjak"
          app: "gymjjak-backend"
          env: "docker"
          __path__: /logs/*.log

    pipeline_stages:
      - regex:
          expression: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3} \[[^\]]+\] (?P<level>INFO|WARN|ERROR|DEBUG|TRACE)'
      - labels:
          level: