spring:
  config:
    activate:
      on-profile: deploy

  datasource:
    url: ${DEPLOY_MYSQL_URL}
    username: ${DEPLOY_MYSQL_USERNAME}
    password: ${DEPLOY_MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

logging:
  level:
    root: info
    com.ssambbong.gymjjak: info
    org.springframework.web: info
    org.springframework.security: info
    org.springframework.messaging: info
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: warn

management:
  endpoint:
    health:
      show-details: never