name: Branch Protection

on:
  push:
    branches:
      - main

jobs:
  prevent-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ] && [ "${{ github.event_name }}" == "push" ]; then
            echo "Direct push to main is not allowed. Please use PR from develop."
            exit 1
          fi